# Generated by Django 4.0.3 on 2022-03-16 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medcards',
            name='exemptid',
        ),
        migrations.RemoveField(
            model_name='shedule',
            name='roomid',
        ),
        migrations.RemoveField(
            model_name='talons',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='talons',
            name='mcid',
        ),
        migrations.RemoveField(
            model_name='talons',
            name='service',
        ),
        migrations.RemoveField(
            model_name='talons',
            name='sheduleid',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='DoctorTypes',
        ),
        migrations.DeleteModel(
            name='Exempts',
        ),
        migrations.DeleteModel(
            name='Medcards',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Shedule',
        ),
        migrations.DeleteModel(
            name='Talons',
        ),
    ]
