# Generated by Django 4.0.3 on 2022-03-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_schedule_free_alter_doctors_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medcards',
            name='year',
            field=models.DateField(verbose_name='Год рождения'),
        ),
    ]
