# Generated by Django 4.0.3 on 2022-03-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_alter_medcards_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='img',
            field=models.ImageField(default='null.jpg', upload_to='img', verbose_name='Аватар'),
            preserve_default=False,
        ),
    ]
