# Generated by Django 4.0.3 on 2022-03-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_doctors_born'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='firstname',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='lastname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='talons',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Примечания (результаты приема)'),
        ),
    ]
